title: Chun-Yi Lee - Interdisciplinary Neuroscience Researcher # 必須在第一行第一欄
email: james820102@gmail.com
description: '跨學科神經科學研究者，專注於環境（自然）對認知功能和決策制定的神經機制影響。'
baseurl: "" 
url: "https://JamesLeeCY.github.io"

# 導航列設定
navbar:
  - title: Home
    url: /
  - title: Research
    url: /research.html
  - title: Publications
    url: /publications.html
  - title: Awards & Leadership
    url: /awards_leadership.html
  - title: Contact
    url: /contact.html
